environment:
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python35"
        - PYTHON: "C:\\Python36"
        - PYTHON: "C:\\Python37"
        - PYTHON: "C:\\Python38"
        - PYTHON: "C:\\Python27-x64"
          DISTUTILS_USE_SDK: "1"
        - PYTHON: "C:\\Python35-x64"
        - PYTHON: "C:\\Python36-x64"
        - PYTHON: "C:\\Python37-x64"
        - PYTHON: "C:\\Python38-x64"

build: off

test_script:
    - "%PYTHON%\\python.exe -m pip install .[test]"
    - "%PYTHON%\\python.exe run_tests.py"
